apiVersion: apps/v1
kind: Deployment

metadata:
  name: policy-engine
  namespace: mlops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: policy-engine

  template:
    metadata:
      labels:
        app: policy-engine

    spec:
      containers:
        - name: policy-engine
          image: policy-engine-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8002