apiVersion: v1
kind: Service

metadata:
  name: policy-engine-service
  namespace: mlops

spec:
  selector:
    app: policy-engine

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002

  type: ClusterIP