apiVersion: v1
kind: Service

metadata:
  name: plant-api-service
  namespace: mlops

spec:
  selector:
    app: plant-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: NodePort